### ISSUE TITLE
[Feature] 구독 및 알림 기능

### ISSUE THREAD

**Issue by Ohjiwoo-lab** [2021-OS-Dev-Project/Gallery#14]
## 설명
미술관 구독 기능 및 구독한 미술관에 새로운 전시회가 나오면 팝업으로 알림을 주는 기능 구현

## Todo List
- [x] Thread 이용해서 엑셀 변화 감지하여 추가된 전시회 출력하는 기능
- [x] 버튼을 눌러 미술관을 구독하면 그 미술관이 추가된 경우만 출력하는 기능
- [ ] 팝업창이 뜰 때 윈도우 알림처럼 우하단에 뜨도록 바꾸기
