### ISSUE TITLE
[Feature] 미술관 구독 및 알림 기능

### ISSUE THREAD

**Issue by Ohjiwoo-lab** [2021-OS-Dev-Project/Gallery#21]
## 설명
미술관을 구독하면 해당 미술관에 전시회 추가 시 알림을 팝업으로 주는 기능

## Todo List
- [x] 엑셀 변화 감지하여 구독한 전시회 추가되면 알림 뜨는 기능
- [x] 알림을 팝업으로 변환
- [x] 미술관이 여러개 일때도 적용되도록 변환
