### ISSUE TITLE
[Feature] 화면전환

### ISSUE THREAD

**Issue by songsuyoung** [2021-OS-Dev-Project/Gallery#9]
## 설명
첫 화면에서 다음 화면으로 이동하는 화면 전환 기능,
모든 Scene을 연결할 때 필요함.
## Todo List

- [x]  main화면 - 로그인 화면 연결 (완료)
- [x] 메뉴의 기능을 누르면 다음 화면으로 이동 (진행중)
- [ ] 애니메이션 효과 (진행중)
